# SOPS configuration file
# This file defines the encryption rules for different paths
creation_rules:
  # Encrypt all secret files in kubernetes directories
  - path_regex: .*secret.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    # Using age encryption (modern and simple)
    # Generate key with: age-keygen -o age.key
    age: >-
      age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p

  # Alternative: Use AWS KMS for production
  # - path_regex: .*secret.*\.yaml$
  #   encrypted_regex: "^(data|stringData)$"
  #   kms: arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab

  # Alternative: Use GCP KMS
  # - path_regex: .*secret.*\.yaml$
  #   encrypted_regex: "^(data|stringData)$"
  #   gcp_kms: projects/PROJECT/locations/global/keyRings/KEYRING/cryptoKeys/KEY