# Configuration for emberstack/reflector with reduced resource requirements
# https://artifacthub.io/packages/helm/emberstack/reflector

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi