apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: ember
  name: reflector
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: "9.0.344"
      sourceRef:
        kind: HelmRepository
        namespace: ember
        name: emberstack
  interval: 5m
  install:
    remediation:
      retries: 30

  valuesFrom:
    - kind: ConfigMap
      name: reflector-values-yaml
