apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - image-update-automation.yaml
images:
  - name: ghcr.io/petrmac/flux-demo/node-service
    newTag: 1.0.1 # {"$imagepolicy": "node-service:node-service:tag"}
