---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-service
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-opentelemetry
  interval: 5m0s
  path: ./flux/apps/demo-service/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: demo-service
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: demo-service
      namespace: demo-service