---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sources
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/sources
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-opentelemetry
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/opentelemetry/minikube
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: opentelemetry-operator
      namespace: opentelemetry
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-opentelemetry-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/opentelemetry-operator/minikube
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: opentelemetry-operator
      namespace: opentelemetry