apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: reflector
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/ember/minikube
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true