apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 1h
  chart:
    spec:
      chart: jaeger
      version: "3.3.1"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: jaeger
      interval: 1h
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    allInOne:
      enabled: true
      image:
        repository: jaegertracing/all-in-one
      args:
        - "--memory.max-traces=10000"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      extraEnv:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
    storage:
      type: memory
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
    service:
      type: ClusterIP
      collector:
        otlp:
          grpc:
            port: 4317
          http:
            port: 4318