apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry-helm-charts
  namespace: opentelemetry-operator
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts