apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: demo-service
type: kubernetes.io/dockerconfigjson
data:
  # This secret will be populated by the setup script
  # It contains credentials for pulling images from ghcr.io
  .dockerconfigjson: e30= # Base64 encoded empty JSON object {}