apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-service
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: demo-service