apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service
  namespace: demo-service
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/component: backend
automountServiceAccountToken: true