apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: postgres
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: demo-service
stringData:
    DB_PASSWORD: "password"
