spring:
  application:
    name: demo-service

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: ${SERVER_MANAGEMENT_PORT:4000}
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: ALWAYS
      access: unrestricted
    metrics:
      access: read_only
    prometheus:
      access: read_only

app:
  version: ${APP_VERSION:1.0.0}
  environment: ${ENVIRONMENT:development}
  greeting:
    prefix: ${GREETING_PREFIX:Hello}
    suffix: ${GREETING_SUFFIX:Welcome to our service!}

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"