spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:demo}
    username: ${DATABASE_USER:demo}
    password: ${DATABASE_PASSWORD:demo123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: ${SERVER_MANAGEMENT_PORT:4000}
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      access: unrestricted
    metrics:
      access: read-only
    prometheus:
      access: read-only

app:
  version: ${APP_VERSION:1.0.0}
  environment: ${ENVIRONMENT:development}
  greeting:
    prefix: ${GREETING_PREFIX:Hello}
    suffix: ${GREETING_SUFFIX:Welcome to our service!}

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"