spring:
  application:
    name: demo-service

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

app:
  version: ${APP_VERSION:1.0.0}
  environment: ${ENVIRONMENT:development}
  greeting:
    prefix: ${GREETING_PREFIX:Hello}
    suffix: ${GREETING_SUFFIX:Welcome to our service!}

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"