apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-service
  namespace: node-service
spec:
  image: ghcr.io/petrmac/flux-demo/node-service
  interval: 5m
  # For public registries, no secretRef needed
  # For private registries, uncomment and configure:
  # secretRef:
  #   name: ghcr-auth
---
# Alternative for Docker Hub
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-service-dockerhub
  namespace: node-service
spec:
  image: docker.io/yourusername/node-service
  interval: 5m
  # secretRef:
  #   name: dockerhub-auth
---
# For local development with Minikube
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-service-local
  namespace: node-service
spec:
  image: node-service
  interval: 1m
  # This will scan the local Docker daemon