apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-service
  namespace: node-service
spec:
  imageRepositoryRef:
    name: node-service
  policy:
    semver:
      range: '>=1.0.0'
---
# Policy for selecting latest patch version in 1.0.x
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-service-patch
  namespace: node-service
spec:
  imageRepositoryRef:
    name: node-service
  policy:
    semver:
      range: '~1.0.0'
---
# Policy for selecting latest minor version in 1.x
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-service-minor
  namespace: node-service
spec:
  imageRepositoryRef:
    name: node-service
  policy:
    semver:
      range: '^1.0.0'
---
# Policy for development/feature branches
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-service-dev
  namespace: node-service
spec:
  imageRepositoryRef:
    name: node-service
  filterTags:
    pattern: '^dev-.*'
    extract: '$0'
  policy:
    alphabetical:
      order: desc
---
# Policy for selecting by timestamp
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-service-latest
  namespace: node-service
spec:
  imageRepositoryRef:
    name: node-service-local
  policy:
    numerical:
      order: asc