apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: node-service
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "YOUR_GITHUB_USERNAME",
          "password": "YOUR_GITHUB_TOKEN",
          "auth": "BASE64_ENCODED_USERNAME:TOKEN"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-auth
  namespace: node-service
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "YOUR_DOCKERHUB_USERNAME",
          "password": "YOUR_DOCKERHUB_TOKEN",
          "auth": "BASE64_ENCODED_USERNAME:TOKEN"
        }
      }
    }