apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-service
  labels:
    app.kubernetes.io/name: node-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: node-service