apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-service

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: demo-service-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - APP_VERSION=1.0.0

replicas:
  - name: demo-service
    count: 3

images:
  - name: demo-service
    newName: ghcr.io/your-org/demo-service
    newTag: 1.0.0 # {"$imagepolicy": "flux-system:demo-service-patch:tag"}